version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: sistema_consultas
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
